import { Linter } from 'eslint'
export const rulesJson: Linter.RulesRecord = {
  'eol-last':                ['error', 'never'],
  'no-multiple-empty-lines': [
    'error',
    { max: 1, maxEOF: 0 },
  ],
  'json/no-duplicate-keys':    'error',
  'json/no-empty-keys':        'error',
  'json/no-unnormalized-keys': 'error',
  'json/no-unsafe-values':     'error',
  'json/no-sort-keys':         'off',
  'json/top-level-interop':    'error',
  'jsonc/key-name-casing':     ['error',
    {
      camelCase:            true,
      PascalCase:           true,
      SCREAMING_SNAKE_CASE: false,
      'kebab-case':         true,
      snake_case:           false,
      ignores:              [
        '^@?.+$',
      ],
    },
  ],
  'jsonc/no-bigint-literals':                'error',
  'jsonc/no-binary-expression':              'error',
  'jsonc/no-binary-numeric-literals':        'error',
  'jsonc/no-comments':                       'error',
  'jsonc/no-escape-sequence-in-identifier':  'error',
  'jsonc/no-hexadecimal-numeric-literals':   'error',
  'jsonc/no-infinity':                       'error',
  'jsonc/no-nan':                            'error',
  'jsonc/no-number-props':                   'error',
  'jsonc/no-numeric-separators':             'error',
  'jsonc/no-octal-numeric-literals':         'error',
  'jsonc/no-parenthesized':                  'error',
  'jsonc/no-plus-sign':                      'error',
  'jsonc/no-regexp-literals':                'error',
  'jsonc/no-template-literals':              'error',
  'jsonc/no-undefined-value':                'error',
  'jsonc/no-unicode-codepoint-escapes':      'error',
  'jsonc/sort-array-values':                 'off',
  'jsonc/sort-keys':                         'off',
  'jsonc/valid-json-number':                 'error',
  'jsonc/vue-custom-block/no-parsing-error': 'error',
  'jsonc/array-bracket-newline':             'off',
  'jsonc/array-bracket-spacing':             'error',
  'jsonc/array-element-newline':             [
    'error',
    {
      ArrayExpression: 'consistent',
      ArrayPattern:    { minItems: 1 },
    },
  ],
  'jsonc/comma-dangle':            ['error', 'never'],
  'jsonc/comma-style':             'error',
  'jsonc/indent':                  ['error', 2],
  'jsonc/key-spacing':             'error',
  'jsonc/no-dupe-keys':            'off',
  'jsonc/no-floating-decimal':     'error',
  'jsonc/no-irregular-whitespace': 'error',
  'jsonc/no-multi-str':            'error',
  'jsonc/no-octal-escape':         'error',
  'jsonc/no-octal':                'error',
  'jsonc/no-sparse-arrays':        'error',
  'jsonc/no-useless-escape':       'error',
  'jsonc/object-curly-newline':    'error',
  'jsonc/object-curly-spacing':    'error',
  'jsonc/object-property-newline': 'error',
  'jsonc/quote-props':             'error',
  'jsonc/quotes':                  'error',
  'jsonc/space-unary-ops':         'error',
}
export const rulesJsonC5: Linter.RulesRecord = {
  ...rulesJson,
  'jsonc/no-comments':  'off',
  'jsonc/comma-dangle': ['error', 'always'],
  'comma-dangle':       'off',
}
